# Generated by Django 2.2.5 on 2019-09-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_time', models.DateTimeField()),
                ('sender', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_time', models.DateTimeField()),
                ('sender', models.CharField(max_length=50)),
                ('recepient', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('received_report', models.IntegerField(default=0)),
                ('read_report', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('nick_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateTimeField()),
                ('relationship_status', models.CharField(max_length=100)),
                ('telephone_number', models.CharField(max_length=15)),
                ('email_addeess', models.CharField(max_length=50)),
                ('resident_address', models.CharField(max_length=200)),
                ('what_makes_you_happy', models.TextField()),
                ('what_makes_you_angry', models.TextField()),
                ('what_makes_you_sad', models.TextField()),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_time', models.DateTimeField()),
                ('tweet', models.TextField()),
                ('tweet_bg', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tweetcomments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.IntegerField()),
                ('comment_by', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('comment_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tweetlikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.IntegerField()),
                ('liker', models.CharField(max_length=50)),
                ('like_time', models.DateTimeField()),
            ],
        ),
    ]
