# Generated by Django 2.2.5 on 2019-09-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception', models.CharField(max_length=50)),
                ('content_type', models.CharField(max_length=50)),
                ('content_for', models.CharField(max_length=50)),
            ],
        ),
    ]
