# Generated by Django 2.2.5 on 2019-09-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_newcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='sender',
            field=models.CharField(default='prior', max_length=50),
            preserve_default=False,
        ),
    ]
