# Generated by Django 2.2.5 on 2019-09-08 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190908_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='tweet_id',
        ),
    ]
