# Generated by Django 2.2.5 on 2019-09-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_users_verificationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMemberships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('group_ID', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='group_ID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
